### ISSUE TITLE
No Button

### ISSUE THREAD

**Issue by matthewdias** [miguelrs/nylas-wunderlist#2]
For some reason the "Add to Wunderlist" Button doesn't show up.

Edit: Seems like this is an issue with the new Nylas Mail. It affects other plugins as well.

**Comment by miguelrs** [comment]
I had kind of abandoned this because I wasn't using N1 anymore, but now they have launched the free version, I'll give it another go, and will try to update this plugin...  
I can't promise it will be very quick though, because I'm pretty busy at the moment 😅

**Comment by plong0** [comment]
I'm using Nylas Mail v1.0.45 and just installed the nylas-wunderlist plugin.

The button shows up, but doesn't seem to do anything.  I've enabled "Mail to Wunderlist" feature in my Wunderlist account, and I can see in the developer console "Sending email to me@wunderlist.com from: <hash string>" followed by a couple messages of "NylasAPI.makeRequest is not a function".

Gonna fork and dig in a little bit.  Thanks for laying down the framework on this.

**Comment by miguelrs** [comment]
Hi @plong0 Probably the Nylas API has changed and the plugin is outdated, sorry about that.

Actually I resumed this project when Nylas became free - I totally refactored the plugin so that now it uses Wunderlist REST API, and not the 'Mail to Wunderlist' feature, so it's much nicer!  
I can fetch my lists and display them in Nylas, but I got stuck when trying to make a `POST` to Wunderlist using Nylas' `Task` class...  
I opened [this GitHub issue](https://github.com/nylas/nylas-mail/issues/3297) about a month ago but nobody replied... Also posted twice in their Slack channel and same thing... If you could help me with that it'd be nice actually!

You can see this is the progress I did (blurred my list names 😉 ):
![nylas_mail](https://cloud.githubusercontent.com/assets/7236632/24268814/0906997a-1007-11e7-8a8d-8148e012536f.png)

Now when I click on a list I need to send the request, and it's where I need to use `Task` -
 well, probably I don't _need_ to, but it seems it's the way Nylas handles asynchronous stuff, so I think it's the way to go... Their docs are a bit shitty and I'm far from being an expert on the matter...

Any contribution would be welcome, but you may want to wait until this new version is released - once I solve that `Task` issue it should be quick...

**Comment by plong0** [comment]
Sounds great!  I would love to pick up helping out wherever you are at.  Any chance you could push your latest to a branch?  I've got a bit of time to try to help you over the Task hurdle - really excited about this Nylas-Wunderlist integration.

PS. I just joined on the Nylas Community Slack team as @plong0  Feel free to DM me on there and we can discuss.

**Comment by miguelrs** [comment]
I just pushed to a branch `refactoring` 😄  - sorry it's just one massive commit...  
I cleaned it up a bit now, but I tried multiple approaches and it's a bit messy - with stuff that may not be used at all...  
Hope you can understand what's going on, and feel free to ask any questions - I'm @miko in Nylas Slack.

PS: I guess you'll need to create an app in Wunderlist API, so you get a client ID and you can generate access tokens for development... there's no authentication implemented yet - another TODO! 😅

**Comment by miguelrs** [comment]
v2 has been just released, which should fix this issue
